### ISSUE TITLE
🐞 [BUG] - <title> Font Size and Text Overflow in Learning Section

### ISSUE THREAD

**Issue by DebapriyaJha** [jfmartinz/ResourceHub#564] opened 2024-05-29 13:19 UTC
### Issue Verification

- [X] I have verified that this is a new bug report.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Describe the bug

In the learning section of the website, the font size of the text appears to be too large, causing it to overflow and extend beyond the boundaries of its containing element. This issue becomes more apparent when hovering over the text, as the text color changes on hover, but some letters are not visible due to the overflow.

### Expected behavior

The expected behavior is for the text in the learning section to be properly contained within its designated element, without any overflow. Additionally, when hovering over the text, the entire text should be visible.

### Steps to reproduce

To address the issue of oversized font and text overflow in the learning section, the following steps could be taken:

1) Adjust Font Size: Reduce the font size of the text to a more appropriate and manageable size that fits comfortably within the designated box or element. This can be achieved by modifying the font-size property in the CSS styles for the relevant elements.
2) Implement Text Overflow Handling: Utilize CSS properties such as overflow and text overflow to control how the text behaves when it exceeds the available space. Options include truncating the text with an ellipsis (text-overflow: ellipsis) or allowing the text to wrap to the next line (overflow: auto or overflow: visible).
3) Hover Styling Adjustments: Review and modify the hover styles applied to the text to ensure that the color change is consistently applied across all visible characters, even when the text overflows or wraps to the next line.

### Additional Context

Before hover:
![3](https://github.com/jfmartinz/ResourceHub/assets/111692420/75507bb5-c556-4e31-901b-45a31dbcbca3)
After hover:
![4](https://github.com/jfmartinz/ResourceHub/assets/111692420/f425d41f-d2b9-4f10-9e8a-b9fb2f6bd87d)

I want to contribute in this project under the gssoc 2024 program. so please assign the labels i.e gssoc24 and the appropriate level to this issue and assign this task to me

**Comment by jfmartinz** [comment] 2024-05-29 13:33
Assigned @DebapriyaJha

**Comment by anuukriti** [comment] 2024-05-29 16:03
@jfmartinz  Please assign this issue to me as well

**Comment by KomalSrivastava** [comment] 2024-05-29 18:49
@jfmartinz Issue Verification:
Verified as a new bug report.

Interest and Organization:
Interested in working on this issue as part of GSSOC 2024 program.

Bug Description:
Text in the learning section of the website appears too large, causing overflow and text to extend beyond its containing element. Hovering over the text further exacerbates the issue, with some letters becoming invisible due to overflow.

Expected Behavior:
Text should be properly contained within its designated element without overflow. Hovering over the text should display the entire text without any visibility issues.

Steps to Reproduce:

Adjust Font Size: Reduce font size to fit within designated element.
Implement Text Overflow Handling: Utilize CSS properties to control text overflow.
Hover Styling Adjustments: Review and modify hover styles for consistent color change.
Please assign labels "gssoc24" and the appropriate level to this issue and assign it to me.

**Comment by DebapriyaJha** [comment] 2024-05-30 15:51
I have made the changes for this issue- 
Before:
![3](https://github.com/jfmartinz/ResourceHub/assets/111692420/7881016e-d681-406a-a7f2-712f6d8f31c8)
![4](https://github.com/jfmartinz/ResourceHub/assets/111692420/05b95474-9743-45a5-a0d2-bfa13206555f)

After:
![6](https://github.com/jfmartinz/ResourceHub/assets/111692420/3934091c-eed3-47b9-9264-ad2c0042a038)
![7](https://github.com/jfmartinz/ResourceHub/assets/111692420/0ed8cbb9-0c3b-4c87-a566-d61b732fd15d)

I only wanted to confirm as per the contribution rules this comes under an error and bug so I should directly create the PR right? If you can clarify it would help me a lot as I am new to open source.

**Closed** 2024-06-02 15:57 UTC
Labels: bug, gssoc, level1
