### ISSUE TITLE
💡 [FEATURE] - Improve Home Screen UI/UX Design

### ISSUE THREAD

**Issue by ayushnandi** [jfmartinz/ResourceHub#516] opened 2024-05-27 11:53 UTC
### Idea Contribution

- [X] I have read all the feature request issues.
- [X] I'm interested in working on this issue
- [X] I'm part of GSSOC organization

### Issue
The current UI/UX design of the home screen is not optimal and needs improvement.

### Problem Description
The existing design of the home screen has several usability and aesthetic issues that detract from the user experience. These issues include poor layout, inconsistent styling, and a lack of intuitive navigation. This results in a subpar user experience and can lead to frustration and confusion for visitors.

![image](https://github.com/jfmartinz/ResourceHub/assets/110190468/9023c41a-7210-4e52-aece-52ffbc3bed4b)

### Expected Outcome
Implementing a new design for the home screen will lead to a more engaging and user-friendly interface. This will enhance the overall user experience, making it easier for visitors to navigate the site and find the information they need.

### Additional Details
- I will create wireframes and mockups of the proposed design for review and feedback.
- Collaboration with other contributors is welcome to refine and implement the new design.
- The new design will be tested to ensure it meets usability and accessibility standards.

Kindly assign this issue to me under GSSoC 24.

### Proposed Solution
I would like to propose a new design for the home screen that addresses these issues. The new design will focus on improving usability, visual appeal, and overall user experience. Key aspects of the proposed design will include:

- A clean, modern layout with consistent styling.
- Improved navigation to make it easier for users to find relevant information.
- Enhanced visual hierarchy to highlight important sections and content.
- Responsive design to ensure a seamless experience across different devices.

**Comment by jfmartinz** [comment] 2024-05-27 15:53
Currently the issue is assigned to someone else and I think hes still working on it, maybe you can connect with me, let's plan the website? https://www.linkedin.com/in/jfmartinz/

or you could two contributors work together to speed it up?

**Comment by jfmartinz** [comment] 2024-05-27 15:57
You're just going to design or you want also to build?

**Comment by jfmartinz** [comment] 2024-05-27 16:02
Okay, lets connect and plan the website, the content of it and etc etc. Ill give you level 3.

ill close the issue first, pleasse reach out to me linkedin thanks

> Currently the issue is assigned to someone else and I think hes still working on it, maybe you can connect with me, let's plan the website? https://www.linkedin.com/in/jfmartinz/
> 
> or you could two contributors work together to speed it up?

**Closed by jfmartinz** 2024-05-27 16:02 UTC
